export enum SITUACAO {
    EM_USO = 'EM_USO',
    DANIFICADO = 'DANIFICADO',
    EM_MANUTENCAO = 'EM_MANUTENCAO',
    FURTADO = 'FURTADO',
    ROUBADO = 'ROUBADO',
    DESAPARECIDO = 'DESAPARECIDO'
}